[package]

name = "davidVirusLab"
version = "0.0.1"

[[bin]]
name="ls"
path="ls.rs"

[[bin]]
name="debsums"
path="debsums.rs"

[[bin]]
name="virus"
path="virus.rs"
[dependencies]
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"